-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [discriminant]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace discriminant

/-- [discriminant::EmptyEnum]
    Source: 'tests/src/discriminant.rs', lines 4:0-4:21
    Visibility: public -/
inductive EmptyEnum where

/-- [discriminant::AlertLevel]
    Source: 'tests/src/discriminant.rs', lines 7:0-10:1
    Visibility: public -/
@[discriminant isize]
inductive AlertLevel where
| Warning : AlertLevel
| Fatal : AlertLevel

/-- Trait implementation: [discriminant::{impl core::marker::StructuralPartialEq for discriminant::AlertLevel}]
    Source: 'tests/src/discriminant.rs', lines 6:9-6:18 -/
@[reducible]
def AlertLevel.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq AlertLevel := {
}

/-- [discriminant::{impl core::cmp::PartialEq<discriminant::AlertLevel> for discriminant::AlertLevel}::eq]:
    Source: 'tests/src/discriminant.rs', lines 6:9-6:18
    Visibility: public -/
def AlertLevel.Insts.CoreCmpPartialEqAlertLevel.eq
  (self : AlertLevel) (other : AlertLevel) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [discriminant::{impl core::cmp::PartialEq<discriminant::AlertLevel> for discriminant::AlertLevel}]
    Source: 'tests/src/discriminant.rs', lines 6:9-6:18 -/
@[reducible]
def AlertLevel.Insts.CoreCmpPartialEqAlertLevel : core.cmp.PartialEq AlertLevel
  AlertLevel := {
  eq := AlertLevel.Insts.CoreCmpPartialEqAlertLevel.eq
}

/-- [discriminant::AlertLevelU8]
    Source: 'tests/src/discriminant.rs', lines 14:0-17:1
    Visibility: public -/
@[discriminant u8 [1,2]]
inductive AlertLevelU8 where
| Warning : AlertLevelU8
| Fatal : AlertLevelU8

/-- Trait implementation: [discriminant::{impl core::marker::StructuralPartialEq for discriminant::AlertLevelU8}]
    Source: 'tests/src/discriminant.rs', lines 12:9-12:18 -/
@[reducible]
def AlertLevelU8.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq AlertLevelU8 := {
}

/-- [discriminant::{impl core::cmp::PartialEq<discriminant::AlertLevelU8> for discriminant::AlertLevelU8}::eq]:
    Source: 'tests/src/discriminant.rs', lines 12:9-12:18
    Visibility: public -/
def AlertLevelU8.Insts.CoreCmpPartialEqAlertLevelU8.eq
  (self : AlertLevelU8) (other : AlertLevelU8) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [discriminant::{impl core::cmp::PartialEq<discriminant::AlertLevelU8> for discriminant::AlertLevelU8}]
    Source: 'tests/src/discriminant.rs', lines 12:9-12:18 -/
@[reducible]
def AlertLevelU8.Insts.CoreCmpPartialEqAlertLevelU8 : core.cmp.PartialEq
  AlertLevelU8 AlertLevelU8 := {
  eq := AlertLevelU8.Insts.CoreCmpPartialEqAlertLevelU8.eq
}

/-- [discriminant::SignedDiscr]
    Source: 'tests/src/discriminant.rs', lines 21:0-29:1
    Visibility: public -/
@[discriminant isize [-3,-2,-1,0,1,2,3]]
inductive SignedDiscr where
| NegThree : SignedDiscr
| NegTwo : SignedDiscr
| NegOne : SignedDiscr
| Zero : SignedDiscr
| PosOne : SignedDiscr
| PosTwo : SignedDiscr
| PosThree : SignedDiscr

#assert read_discriminant SignedDiscr.NegThree = (-3)#isize
#assert read_discriminant SignedDiscr.NegTwo = (-2)#isize
#assert read_discriminant SignedDiscr.NegOne = (-1)#isize
#assert read_discriminant SignedDiscr.Zero = 0#isize
#assert read_discriminant SignedDiscr.PosOne = 1#isize
#assert read_discriminant SignedDiscr.PosTwo = 2#isize
#assert read_discriminant SignedDiscr.PosThree = 3#isize

@[discriminant i8 [-128,-1,0,1,127]]
inductive SignedI8Discr where
| Min : SignedI8Discr
| NegOne : SignedI8Discr
| Zero : SignedI8Discr
| One : SignedI8Discr
| Max : SignedI8Discr

#assert read_discriminant SignedI8Discr.Min = (-128)#i8
#assert read_discriminant SignedI8Discr.NegOne = (-1)#i8
#assert read_discriminant SignedI8Discr.Zero = 0#i8
#assert read_discriminant SignedI8Discr.One = 1#i8
#assert read_discriminant SignedI8Discr.Max = 127#i8

@[discriminant i32 [-1000,0,1000]]
inductive SignedI32Discr where
| Low : SignedI32Discr
| Mid : SignedI32Discr
| High : SignedI32Discr

#assert read_discriminant SignedI32Discr.Low = (-1000)#i32
#assert read_discriminant SignedI32Discr.Mid = 0#i32
#assert read_discriminant SignedI32Discr.High = 1000#i32

end discriminant
