-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [preconditions]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace preconditions

/-- [preconditions::ComplexStruct]
    Source: 'tests/src/preconditions.rs', lines 6:0-8:1
    Visibility: public -/
structure ComplexStruct where
  x : Std.I32

/-- [preconditions::{impl core::clone::Clone for preconditions::ComplexStruct}::clone]:
    Source: 'tests/src/preconditions.rs', lines 5:15-5:20
    Visibility: public -/
def ComplexStruct.Insts.CoreCloneClone.clone
  (self : ComplexStruct) : Result ComplexStruct := do
  ok self

/-- Trait implementation: [preconditions::{impl core::clone::Clone for preconditions::ComplexStruct}]
    Source: 'tests/src/preconditions.rs', lines 5:15-5:20 -/
@[reducible]
def ComplexStruct.Insts.CoreCloneClone : core.clone.Clone ComplexStruct := {
  clone := ComplexStruct.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [preconditions::{impl core::marker::Copy for preconditions::ComplexStruct}]
    Source: 'tests/src/preconditions.rs', lines 5:9-5:13 -/
@[reducible]
def ComplexStruct.Insts.CoreMarkerCopy : core.marker.Copy ComplexStruct := {
  cloneInst := ComplexStruct.Insts.CoreCloneClone
}

/-- [preconditions::bar]:
    Source: 'tests/src/preconditions.rs', lines 10:0-12:1
    Visibility: public -/
def bar (b : ComplexStruct) : Result Bool := do
  ok (b.x > 0#i32)

/-- [preconditions::foo]:
    Source: 'tests/src/preconditions.rs', lines 15:0-19:1
    Visibility: public -/
def Φ'foo (a : Std.I32) (b : ComplexStruct) : Result Unit := do
  massert (a > 12#i32)
  let b1 ← bar b
  massert b1
  ok ()

/-- [preconditions::foo]:
    Source: 'tests/src/preconditions.rs', lines 15:0-19:1
    Visibility: public -/
def foo (a : Std.I32) (b : ComplexStruct) : Result Std.I32 := do
  Φ'foo a b
  a + b.x

/-- [preconditions::left_shift_one]:
    Source: 'tests/src/preconditions.rs', lines 22:0-27:1
    Visibility: public -/
def Φ'left_shift_one (v : Std.I32) : Result Unit := do
  massert (v >= 0#i32)
  massert (v < 1024#i32)
  ok ()

/-- [preconditions::left_shift_one]:
    Source: 'tests/src/preconditions.rs', lines 22:0-27:1
    Visibility: public -/
def left_shift_one (v : Std.I32) : Result Std.I32 := do
  Φ'left_shift_one v
  let r ← v <<< 1#i32
  let i ← v * 2#i32
  massert (r = i)
  ok r

/-- [preconditions::with_debug_assert]:
    Source: 'tests/src/preconditions.rs', lines 30:0-34:1
    Visibility: public -/
def Φ'with_debug_assert (x : Std.U32) (y : Std.U32) : Result Unit := do
  massert (x <= 1000#u32)
  massert (y <= 1000#u32)
  ok ()

/-- [preconditions::with_debug_assert]:
    Source: 'tests/src/preconditions.rs', lines 30:0-34:1
    Visibility: public -/
def with_debug_assert (x : Std.U32) (y : Std.U32) : Result Std.U32 := do
  Φ'with_debug_assert x y
  x + y

/-- [preconditions::with_assert_eq_ne]:
    Source: 'tests/src/preconditions.rs', lines 37:0-41:1
    Visibility: public -/
def Φ'with_assert_eq_ne
  (a : Std.I32) (b : Std.I32) (c : Std.I32) : Result Unit := do
  massert (a = b)
  massert (¬ (c = 0#i32))
  ok ()

/-- [preconditions::with_assert_eq_ne]:
    Source: 'tests/src/preconditions.rs', lines 37:0-41:1
    Visibility: public -/
def with_assert_eq_ne
  (a : Std.I32) (b : Std.I32) (c : Std.I32) : Result Std.I32 := do
  Φ'with_assert_eq_ne a b c
  a + c

/-- [preconditions::partial_extraction]:
    Source: 'tests/src/preconditions.rs', lines 45:0-50:1
    Visibility: public -/
def Φ'partial_extraction (x : Std.I32) : Result Unit := do
  massert (x > 0#i32)
  ok ()

/-- [preconditions::partial_extraction]:
    Source: 'tests/src/preconditions.rs', lines 45:0-50:1
    Visibility: public -/
def partial_extraction (x : Std.I32) : Result Std.I32 := do
  Φ'partial_extraction x
  let y ← x + 1#i32
  massert (y < 100#i32)
  ok y

/-- [preconditions::no_precondition]:
    Source: 'tests/src/preconditions.rs', lines 53:0-57:1
    Visibility: public -/
def no_precondition (x : Std.I32) : Result Std.I32 := do
  let y ← x * 2#i32
  massert (y > 0#i32)
  ok y

/-- [preconditions::make_val]:
    Source: 'tests/src/preconditions.rs', lines 62:0-64:1
    Visibility: public -/
def make_val : Result Std.I32 := do
  ok 0#i32

/-- [preconditions::duplicate_call_after_assert]:
    Source: 'tests/src/preconditions.rs', lines 66:0-70:1
    Visibility: public -/
def Φ'duplicate_call_after_assert : Result Unit := do
  let left_val ← make_val
  massert (left_val = 0#i32)
  ok ()

/-- [preconditions::duplicate_call_after_assert]:
    Source: 'tests/src/preconditions.rs', lines 66:0-70:1
    Visibility: public -/
def duplicate_call_after_assert : Result Unit := do
  Φ'duplicate_call_after_assert
  let val ← make_val
  massert (val = 0#i32)

/-- [preconditions::with_aeneas_require]:
    Source: 'tests/src/preconditions.rs', lines 81:0-88:1
    Visibility: public -/
def Φ'with_aeneas_require (x : Std.I32) (y : Std.I32) : Result Unit := do
  massert (x > 0#i32)
  massert (y > 0#i32)
  let sum ← x + y
  massert (sum > 10#i32)
  ok ()

/-- [preconditions::with_aeneas_require]:
    Source: 'tests/src/preconditions.rs', lines 81:0-88:1
    Visibility: public -/
def with_aeneas_require (x : Std.I32) (y : Std.I32) : Result Std.I32 := do
  Φ'with_aeneas_require x y
  let sum ← x + y
  massert (y > 0#i32)
  ok sum

end preconditions
